services:
  - type: web
    name: smart-urban-vitality
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5001
      # Secret environment variables to be set in Render dashboard
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: STATIONS
        value: '{
          "1": {"name": "Garching/IOT-Lab", "location": {"lat": 48.26264036847362, "lng": 11.668331022751858}},
          "2": {"name": "Garching/Basketball Court", "location": {"lat": 48.26364466819253, "lng": 11.668459013506432}},
          "3": {"name": "Garching/IOT-Lab Balcony", "location": {"lat": 48.26271268490997, "lng": 11.66840813626192}}
        }'
      - key: THRESHOLDS
        value: '{
          "temperature": {"min": -15, "max": 45, "warning": 30},
          "humidity": {"min": 0, "max": 100},
          "uv_index": {"min": 0, "max": 12, "warning": 5},
          "air_quality": {"min": 0, "max": 100},
          "co2e": {"min": 200, "max": 3000},
          "fill_level": {"min": 0, "max": 100, "warning": 20}
        }'
      - key: UPDATE_INTERVALS
        value: '{
          "charts": 30000,
          "alerts": 30000
        }'
    healthCheckPath: /health
    autoDeploy: true 