services:
  - type: web
    name: smart-urban-vitality
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5001
      - key: GOOGLE_MAPS_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    preDeployCommand: flask db upgrade 